---
    name: License Header Checker
    
    on: [push, pull_request]
    
    jobs:
      license-header-checker:
        runs-on: ubuntu-latest
        steps:
          - uses: actions/checkout@f43a0e5ff2bd294095638e18286ca9a3d1956744 # v3
          - name: Check License Header
            run: npx @kt3k/license-checker
